#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jbanimalitosv2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="animalitos")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertSorteos__(Sorteos__ instance);
    partial void UpdateSorteos__(Sorteos__ instance);
    partial void DeleteSorteos__(Sorteos__ instance);
    partial void InsertHorarios(Horarios instance);
    partial void UpdateHorarios(Horarios instance);
    partial void DeleteHorarios(Horarios instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Jbanimalitosv2.Properties.Settings.Default.animalitosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sorteos__> Sorteos__
		{
			get
			{
				return this.GetTable<Sorteos__>();
			}
		}
		
		public System.Data.Linq.Table<Horarios> Horarios
		{
			get
			{
				return this.GetTable<Horarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Sorteos\r\n]")]
	public partial class Sorteos__ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSorteos;
		
		private string _sorteo;
		
		private System.Nullable<double> _minimo;
		
		private System.Nullable<double> _maximo;
		
		private System.Nullable<double> _pagar;
		
		private string _estatus;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSorteosChanging(int value);
    partial void OnIdSorteosChanged();
    partial void OnsorteoChanging(string value);
    partial void OnsorteoChanged();
    partial void OnminimoChanging(System.Nullable<double> value);
    partial void OnminimoChanged();
    partial void OnmaximoChanging(System.Nullable<double> value);
    partial void OnmaximoChanged();
    partial void OnpagarChanging(System.Nullable<double> value);
    partial void OnpagarChanged();
    partial void OnestatusChanging(string value);
    partial void OnestatusChanged();
    #endregion
		
		public Sorteos__()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSorteos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSorteos
		{
			get
			{
				return this._IdSorteos;
			}
			set
			{
				if ((this._IdSorteos != value))
				{
					this.OnIdSorteosChanging(value);
					this.SendPropertyChanging();
					this._IdSorteos = value;
					this.SendPropertyChanged("IdSorteos");
					this.OnIdSorteosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sorteo", DbType="VarChar(MAX)")]
		public string sorteo
		{
			get
			{
				return this._sorteo;
			}
			set
			{
				if ((this._sorteo != value))
				{
					this.OnsorteoChanging(value);
					this.SendPropertyChanging();
					this._sorteo = value;
					this.SendPropertyChanged("sorteo");
					this.OnsorteoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimo", DbType="Float")]
		public System.Nullable<double> minimo
		{
			get
			{
				return this._minimo;
			}
			set
			{
				if ((this._minimo != value))
				{
					this.OnminimoChanging(value);
					this.SendPropertyChanging();
					this._minimo = value;
					this.SendPropertyChanged("minimo");
					this.OnminimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maximo", DbType="Float")]
		public System.Nullable<double> maximo
		{
			get
			{
				return this._maximo;
			}
			set
			{
				if ((this._maximo != value))
				{
					this.OnmaximoChanging(value);
					this.SendPropertyChanging();
					this._maximo = value;
					this.SendPropertyChanged("maximo");
					this.OnmaximoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pagar", DbType="Float")]
		public System.Nullable<double> pagar
		{
			get
			{
				return this._pagar;
			}
			set
			{
				if ((this._pagar != value))
				{
					this.OnpagarChanging(value);
					this.SendPropertyChanging();
					this._pagar = value;
					this.SendPropertyChanged("pagar");
					this.OnpagarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estatus", DbType="NVarChar(1)")]
		public string estatus
		{
			get
			{
				return this._estatus;
			}
			set
			{
				if ((this._estatus != value))
				{
					this.OnestatusChanging(value);
					this.SendPropertyChanging();
					this._estatus = value;
					this.SendPropertyChanged("estatus");
					this.OnestatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Horarios")]
	public partial class Horarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _IdSorteo;
		
		private System.Nullable<System.TimeSpan> _Horario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdSorteoChanging(System.Nullable<int> value);
    partial void OnIdSorteoChanged();
    partial void OnHorarioChanging(System.Nullable<System.TimeSpan> value);
    partial void OnHorarioChanged();
    #endregion
		
		public Horarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSorteo", DbType="Int")]
		public System.Nullable<int> IdSorteo
		{
			get
			{
				return this._IdSorteo;
			}
			set
			{
				if ((this._IdSorteo != value))
				{
					this.OnIdSorteoChanging(value);
					this.SendPropertyChanging();
					this._IdSorteo = value;
					this.SendPropertyChanged("IdSorteo");
					this.OnIdSorteoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Horario", DbType="Time")]
		public System.Nullable<System.TimeSpan> Horario
		{
			get
			{
				return this._Horario;
			}
			set
			{
				if ((this._Horario != value))
				{
					this.OnHorarioChanging(value);
					this.SendPropertyChanging();
					this._Horario = value;
					this.SendPropertyChanged("Horario");
					this.OnHorarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
